name: lp_machine_test
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sizer: ^3.0.5
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen: ^5.8.0



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
        - asset: assets/fonts/AirbnbCereal_W_Bk.otf
        - asset: assets/fonts/AirbnbCereal_W_Blk.otf
        - asset: assets/fonts/AirbnbCereal_W_lt.otf
        - asset: assets/fonts/AirbnbCereal_W_md.otf
        - asset: assets/fonts/AirbnbCereal_W_XBd.otf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
